MNT: Re-rendered with conda-build 3.21.4, conda-smithy 3.10.1.post.dev5, and conda-forge-pinning 2021.05.07.14.12.29

diff --git a/.azure-pipelines/azure-pipelines-linux.yml b/.azure-pipelines/azure-pipelines-linux.yml
--- a/.azure-pipelines/azure-pipelines-linux.yml
+++ b/.azure-pipelines/azure-pipelines-linux.yml
@@ -11,6 +11,7 @@ jobs:
       linux_64_:
         CONFIG: linux_64_
         UPLOAD_PACKAGES: 'True'
+        SHORT_CONFIG: linux_64_
         DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
   timeoutInMinutes: 360
 
@@ -39,15 +40,44 @@ jobs:
       FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
       STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
   - script: |
-        full_artifact_name="conda_artifacts_$(build.BuildId)_$(CONFIG)"
-        artifact_name=`echo "$full_artifact_name" | head -c 80`
-        echo "##vso[task.setVariable variable=ARTIFACT_NAME]$artifact_name"
-        if [ -d build_artifacts ]; then
-          echo "##vso[task.setVariable variable=CONDA_BLD_DIR_EXISTS]true"
+        # Set the artifact name, specialized for this particular job run.
+        ARTIFACT_NAME="conda_artifacts_$(build.BuildNumber).$(system.JobAttempt)_$(CONFIG)"
+        if [[ ${#ARTIFACT_NAME} -gt 80 ]]; then
+          ARTIFACT_NAME="conda_artifacts_$(build.BuildNumber).$(system.JobAttempt)_$(SHORT_CONFIG)"
         fi
-    displayName: Check for conda build artifacts
+        echo "##vso[task.setVariable variable=ARTIFACT_NAME]$ARTIFACT_NAME"
+        echo "ARTIFACT_NAME: $ARTIFACT_NAME"
+
+        # Check that the conda-build directory exists for archiving.
+        ARTIFACT_DIR=build_artifacts
+        if [ -d "$ARTIFACT_DIR" ]; then
+          # remove caches to save some artifact space
+          rm -rf $ARTIFACT_DIR/git_cache
+          rm -rf $ARTIFACT_DIR/pip_cache
+          rm -rf $ARTIFACT_DIR/src_cache
+          # delete broken symlinks so that artifact publishing doesn't fail
+          find $ARTIFACT_DIR -type l -exec test ! -e {} \; -delete
+        else
+          echo "##vso[task.logissue type=error]conda-build directory does not exist"
+          exit 1
+        fi
+        echo "##vso[task.setVariable variable=ARTIFACT_PATH]$ARTIFACT_DIR"
+        echo "ARTIFACT_DIR: $ARTIFACT_DIR"
+
+        if [ $AGENT_JOBSTATUS == "Failed" ]; then
+          # Create a zip archive to use as the artifact.
+          ARTIFACT_ZIP="$(Build.ArtifactStagingDirectory)/${ARTIFACT_NAME}.zip"
+          cd "$ARTIFACT_DIR"
+          zip -r -y -q "$ARTIFACT_ZIP" . -x '*.git/*' '*_*_env*/*' '*_cache/*'
+          echo "##vso[task.setVariable variable=ARTIFACT_PATH]$ARTIFACT_ZIP"
+          echo "ARTIFACT_ZIP: $ARTIFACT_ZIP"
+        fi
+    displayName: Prepare conda build artifacts
     condition: succeededOrFailed()
 
-  - publish: build_artifacts/
-    artifact: $(ARTIFACT_NAME)
-    condition: eq(variables.CONDA_BLD_DIR_EXISTS, 'true')
+  - task: PublishPipelineArtifact@1
+    displayName: Store conda build artifacts
+    condition: not(eq(variables.ARTIFACT_PATH, ''))
+    inputs:
+      targetPath: $(ARTIFACT_PATH)
+      artifactName: $(ARTIFACT_NAME)
