MNT: Re-rendered with conda-build 3.21.4, conda-smithy 3.10.1.post.dev11, and conda-forge-pinning 2021.06.09.12.51.26

diff --git a/.azure-pipelines/azure-pipelines-linux.yml b/.azure-pipelines/azure-pipelines-linux.yml
--- a/.azure-pipelines/azure-pipelines-linux.yml
+++ b/.azure-pipelines/azure-pipelines-linux.yml
@@ -12,6 +12,7 @@ jobs:
         CONFIG: linux_64_
         UPLOAD_PACKAGES: 'True'
         DOCKER_IMAGE: quay.io/condaforge/linux-anvil-comp7
+        SHORT_CONFIG: linux_64_
   timeoutInMinutes: 360
 
   steps:
@@ -39,15 +40,62 @@ jobs:
       FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
       STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
   - script: |
-        full_artifact_name="conda_artifacts_$(build.BuildId)_$(CONFIG)"
-        artifact_name=`echo "$full_artifact_name" | head -c 80`
-        echo "##vso[task.setVariable variable=ARTIFACT_NAME]$artifact_name"
-        if [ -d build_artifacts ]; then
-          echo "##vso[task.setVariable variable=CONDA_BLD_DIR_EXISTS]true"
+        # Set the artifact name, specialized for this particular job run.
+        ARTIFACT_UNIQUE_ID="$(build.BuildNumber).$(system.JobAttempt)_$(CONFIG)"
+        if [[ ${#ARTIFACT_UNIQUE_ID} -gt 80 ]]; then
+          ARTIFACT_UNIQUE_ID="$(build.BuildNumber).$(system.JobAttempt)_$(SHORT_CONFIG)"
         fi
-    displayName: Check for conda build artifacts
+        # prefix should be <= 20 characters so the artifact name doesn't exceed 100
+        BLD_ARTIFACT_PREFIX="conda_artifacts_"
+        BLD_ARTIFACT_NAME="${BLD_ARTIFACT_PREFIX}${ARTIFACT_UNIQUE_ID}"
+        echo "##vso[task.setVariable variable=BLD_ARTIFACT_NAME]$BLD_ARTIFACT_NAME"
+        echo "BLD_ARTIFACT_NAME: $BLD_ARTIFACT_NAME"
+
+        # Check that the conda-build directory exists for archiving.
+        BLD_ARTIFACT_DIR=build_artifacts
+        if [ -d "$BLD_ARTIFACT_DIR" ]; then
+          # remove caches to save some artifact space
+          rm -rf $BLD_ARTIFACT_DIR/git_cache
+          rm -rf $BLD_ARTIFACT_DIR/pip_cache
+          rm -rf $BLD_ARTIFACT_DIR/src_cache
+          # delete broken symlinks so that artifact publishing doesn't fail
+          find $BLD_ARTIFACT_DIR -type l -exec test ! -e {} \; -delete
+        else
+          echo "##vso[task.logissue type=error]conda-build directory does not exist"
+          exit 1
+        fi
+        echo "##vso[task.setVariable variable=BLD_ARTIFACT_PATH]$BLD_ARTIFACT_DIR"
+        echo "BLD_ARTIFACT_DIR: $BLD_ARTIFACT_DIR"
+
+        if [ $AGENT_JOBSTATUS == "Failed" ]; then
+          # Create a zip archive to use as the conda build artifact.
+          BLD_ARTIFACT_ZIP="$(Build.ArtifactStagingDirectory)/${BLD_ARTIFACT_NAME}.zip"
+          cd "$BLD_ARTIFACT_DIR"
+          zip -r -y -q "$BLD_ARTIFACT_ZIP" . -x '*.git/*' '*_*_env*/*' '*_cache/*'
+          echo "##vso[task.setVariable variable=BLD_ARTIFACT_PATH]$BLD_ARTIFACT_ZIP"
+          echo "BLD_ARTIFACT_ZIP: $BLD_ARTIFACT_ZIP"
+
+          # Create a zip archive to use as the conda env artifact
+          ENV_ARTIFACT_PREFIX="conda_envs_"
+          ENV_ARTIFACT_NAME="${ENV_ARTIFACT_PREFIX}${ARTIFACT_UNIQUE_ID}"
+          ENV_ARTIFACT_ZIP="$(Build.ArtifactStagingDirectory)/${ENV_ARTIFACT_NAME}.zip"
+          zip -r -y -q "$ENV_ARTIFACT_ZIP" . -i '*_*_env*/*'
+          echo "##vso[task.setVariable variable=ENV_ARTIFACT_PATH]$ENV_ARTIFACT_ZIP"
+          echo "ENV_ARTIFACT_ZIP: $ENV_ARTIFACT_ZIP"
+        fi
+    displayName: Prepare conda build artifacts
     condition: succeededOrFailed()
 
-  - publish: build_artifacts/
-    artifact: $(ARTIFACT_NAME)
-    condition: eq(variables.CONDA_BLD_DIR_EXISTS, 'true')
+  - task: PublishPipelineArtifact@1
+    displayName: Store conda build artifacts
+    condition: not(eq(variables.BLD_ARTIFACT_PATH, ''))
+    inputs:
+      targetPath: $(BLD_ARTIFACT_PATH)
+      artifactName: $(BLD_ARTIFACT_NAME)
+
+  - task: PublishPipelineArtifact@1
+    displayName: Store conda build environment artifacts
+    condition: not(eq(variables.ENV_ARTIFACT_PATH, ''))
+    inputs:
+      targetPath: $(ENV_ARTIFACT_PATH)
+      artifactName: $(ENV_ARTIFACT_NAME)
